
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
        - POSTGRES_DB:${POSTGRES_DB}
        - POSTGRES_USER:${POSTGRES_USER}
        - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - progresDB:/var/lib/postgresql/data
    env_file:
      - .env
  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --requirepass "Hire_me"
    ports:
      - '6379:6379'
    volumes:
      - redisDB:/data
    depends_on:
      - postgres 
    env_file:
     - .env

volumes:
  progresDB:
  redisDB:
